/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { Row } from "@rocicorp/zero";
import { createBuilder } from "@rocicorp/zero";
import type { ZeroCustomType } from "drizzle-zero";
import type { default as zeroSchema } from "./drizzle-zero.config";

/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
  tables: {
    classCoordinators: {
      name: "classCoordinators",
      columns: {
        coordinatorId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "classCoordinators",
            "coordinatorId"
          >,
          serverName: "user_id",
        },
        classId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "classCoordinators",
            "classId"
          >,
          serverName: "class_id",
        },
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "classCoordinators",
            "createdAt"
          >,
          serverName: "created_at",
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "classCoordinators",
            "updatedAt"
          >,
          serverName: "updated_at",
        },
      },
      primaryKey: ["coordinatorId", "classId"],
      serverName: "class_coordinators",
    },
    classes: {
      name: "classes",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "classes",
            "id"
          >,
        },
        name: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "classes",
            "name"
          >,
        },
        description: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "classes",
            "description"
          >,
        },
        guardianId: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "classes",
            "guardianId"
          >,
          serverName: "guardian_id",
        },
        trainerId: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "classes",
            "trainerId"
          >,
          serverName: "trainer_id",
        },
        trainerCostPerSession: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "classes",
            "trainerCostPerSession"
          >,
          serverName: "trainer_cost_per_session",
        },
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "classes",
            "createdAt"
          >,
          serverName: "created_at",
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "classes",
            "updatedAt"
          >,
          serverName: "updated_at",
        },
      },
      primaryKey: ["id"],
    },
    invoicedSessions: {
      name: "invoicedSessions",
      columns: {
        invoiceId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "invoicedSessions",
            "invoiceId"
          >,
          serverName: "invoice_id",
        },
        sessionId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "invoicedSessions",
            "sessionId"
          >,
          serverName: "session_id",
        },
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "invoicedSessions",
            "createdAt"
          >,
          serverName: "created_at",
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "invoicedSessions",
            "updatedAt"
          >,
          serverName: "updated_at",
        },
      },
      primaryKey: ["invoiceId", "sessionId"],
      serverName: "invoiced_sessions",
    },
    invoices: {
      name: "invoices",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "invoices",
            "id"
          >,
        },
        classId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "invoices",
            "classId"
          >,
          serverName: "class_id",
        },
        invoicePath: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "invoices",
            "invoicePath"
          >,
          serverName: "invoice_path",
        },
        approved: {
          type: "boolean",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "invoices",
            "approved"
          >,
        },
        paid: {
          type: "boolean",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "invoices",
            "paid"
          >,
        },
        paymentScreenshot: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "invoices",
            "paymentScreenshot"
          >,
          serverName: "payment_screenshot",
        },
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "invoices",
            "createdAt"
          >,
          serverName: "created_at",
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "invoices",
            "updatedAt"
          >,
          serverName: "updated_at",
        },
      },
      primaryKey: ["id"],
    },
    participants: {
      name: "participants",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "participants",
            "id"
          >,
        },
        name: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "participants",
            "name"
          >,
        },
        dob: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "participants",
            "dob"
          >,
        },
        age: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "participants",
            "age"
          >,
        },
        gender: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "participants",
            "gender"
          >,
        },
        classId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "participants",
            "classId"
          >,
          serverName: "class_id",
        },
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "participants",
            "createdAt"
          >,
          serverName: "created_at",
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "participants",
            "updatedAt"
          >,
          serverName: "updated_at",
        },
      },
      primaryKey: ["id"],
    },
    sessionParticipants: {
      name: "sessionParticipants",
      columns: {
        participantId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "sessionParticipants",
            "participantId"
          >,
          serverName: "participant_id",
        },
        sessionId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "sessionParticipants",
            "sessionId"
          >,
          serverName: "session_id",
        },
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "sessionParticipants",
            "createdAt"
          >,
          serverName: "created_at",
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "sessionParticipants",
            "updatedAt"
          >,
          serverName: "updated_at",
        },
      },
      primaryKey: ["participantId", "sessionId"],
      serverName: "session_participants",
    },
    sessions: {
      name: "sessions",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "sessions",
            "id"
          >,
        },
        classId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "sessions",
            "classId"
          >,
          serverName: "class_id",
        },
        photo: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "sessions",
            "photo"
          >,
        },
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "sessions",
            "createdAt"
          >,
          serverName: "created_at",
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "sessions",
            "updatedAt"
          >,
          serverName: "updated_at",
        },
      },
      primaryKey: ["id"],
    },
    users: {
      name: "users",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "users",
            "id"
          >,
        },
        firstName: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "users",
            "firstName"
          >,
          serverName: "first_name",
        },
        lastName: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "users",
            "lastName"
          >,
          serverName: "last_name",
        },
        role: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "users",
            "role"
          >,
        },
        phoneNumber: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "users",
            "phoneNumber"
          >,
          serverName: "phone_number",
        },
        email: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "users",
            "email"
          >,
        },
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "users",
            "createdAt"
          >,
          serverName: "created_at",
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "users",
            "updatedAt"
          >,
          serverName: "updated_at",
        },
      },
      primaryKey: ["id"],
    },
  },
  relationships: {
    classCoordinators: {
      class: [
        {
          sourceField: ["classId"],
          destField: ["id"],
          destSchema: "classes",
          cardinality: "one",
        },
      ],
      coordinator: [
        {
          sourceField: ["coordinatorId"],
          destField: ["id"],
          destSchema: "users",
          cardinality: "one",
        },
      ],
    },
    classes: {
      coordinators: [
        {
          sourceField: ["id"],
          destField: ["classId"],
          destSchema: "classCoordinators",
          cardinality: "many",
        },
      ],
      trainer: [
        {
          sourceField: ["trainerId"],
          destField: ["id"],
          destSchema: "users",
          cardinality: "one",
        },
      ],
      guardian: [
        {
          sourceField: ["guardianId"],
          destField: ["id"],
          destSchema: "users",
          cardinality: "one",
        },
      ],
      participants: [
        {
          sourceField: ["id"],
          destField: ["classId"],
          destSchema: "participants",
          cardinality: "many",
        },
      ],
      sessions: [
        {
          sourceField: ["id"],
          destField: ["classId"],
          destSchema: "sessions",
          cardinality: "many",
        },
      ],
      invoices: [
        {
          sourceField: ["id"],
          destField: ["classId"],
          destSchema: "invoices",
          cardinality: "many",
        },
      ],
    },
    invoicedSessions: {
      session: [
        {
          sourceField: ["sessionId"],
          destField: ["id"],
          destSchema: "sessions",
          cardinality: "one",
        },
      ],
      invoice: [
        {
          sourceField: ["invoiceId"],
          destField: ["id"],
          destSchema: "invoices",
          cardinality: "one",
        },
      ],
    },
    invoices: {
      class: [
        {
          sourceField: ["classId"],
          destField: ["id"],
          destSchema: "classes",
          cardinality: "one",
        },
      ],
      sessions: [
        {
          sourceField: ["id"],
          destField: ["invoiceId"],
          destSchema: "invoicedSessions",
          cardinality: "many",
        },
      ],
    },
    participants: {
      class: [
        {
          sourceField: ["classId"],
          destField: ["id"],
          destSchema: "classes",
          cardinality: "one",
        },
      ],
      participatedSessions: [
        {
          sourceField: ["id"],
          destField: ["participantId"],
          destSchema: "sessionParticipants",
          cardinality: "many",
        },
      ],
    },
    sessionParticipants: {
      session: [
        {
          sourceField: ["sessionId"],
          destField: ["id"],
          destSchema: "sessions",
          cardinality: "one",
        },
      ],
      participant: [
        {
          sourceField: ["participantId"],
          destField: ["id"],
          destSchema: "participants",
          cardinality: "one",
        },
      ],
    },
    sessions: {
      participants: [
        {
          sourceField: ["id"],
          destField: ["sessionId"],
          destSchema: "sessionParticipants",
          cardinality: "many",
        },
      ],
      class: [
        {
          sourceField: ["classId"],
          destField: ["id"],
          destSchema: "classes",
          cardinality: "one",
        },
      ],
      invoice: [
        {
          sourceField: ["id"],
          destField: ["sessionId"],
          destSchema: "invoicedSessions",
          cardinality: "one",
        },
      ],
    },
    users: {
      coordinatingClasses: [
        {
          sourceField: ["id"],
          destField: ["coordinatorId"],
          destSchema: "classCoordinators",
          cardinality: "many",
        },
      ],
      trainingClasses: [
        {
          sourceField: ["id"],
          destField: ["trainerId"],
          destSchema: "classes",
          cardinality: "many",
        },
      ],
      guardianingClasses: [
        {
          sourceField: ["id"],
          destField: ["trainerId"],
          destSchema: "classes",
          cardinality: "many",
        },
      ],
    },
  },
  enableLegacyQueries: true,
  enableLegacyMutators: true,
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
/**
 * Represents a row from the "classCoordinators" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ClassCoordinator = Row<Schema["tables"]["classCoordinators"]>;
/**
 * Represents a row from the "classes" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Class = Row<Schema["tables"]["classes"]>;
/**
 * Represents a row from the "invoicedSessions" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type InvoicedSession = Row<Schema["tables"]["invoicedSessions"]>;
/**
 * Represents a row from the "invoices" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Invoice = Row<Schema["tables"]["invoices"]>;
/**
 * Represents a row from the "participants" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Participant = Row<Schema["tables"]["participants"]>;
/**
 * Represents a row from the "sessionParticipants" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type SessionParticipant = Row<Schema["tables"]["sessionParticipants"]>;
/**
 * Represents a row from the "sessions" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Session = Row<Schema["tables"]["sessions"]>;
/**
 * Represents a row from the "users" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type User = Row<Schema["tables"]["users"]>;

/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const builder = createBuilder(schema);
